version: 2
updates:
  - package-ecosystem: "npm"
    directoy: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Timeraa"
      - "TheDropX"
    commit-message:
      prefix: "🔼"
      prefix-development: "🔼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
