name: DePloY
on:
  push:
    branches: main
    paths:
      - "**/*.yml"
      - "src/**/*"
      - "**.ts"
      - "**.json"
jobs:
  DePloY:
    strategy:
      matrix:
        host: ${{secrets.SSHHOSTS}}
    runs-on: "ubuntu-latest"
    steps:
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ matrix.host }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            cd /home/API
            git reset --hard
            git pull
            yarn run init
            pm2 reload /home/PreMiD/ecosystem.config.js --only API
