name: Build Docker Image
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: Timeraa
        password: ${{ secrets.GH_TOKEN }}
        registry: docker.pkg.github.com
        repository: premid/api/api
        tags: latest
